## precisa instalar a extensão rest client
## aqui não vai rodar bem, estou deixando apenas para 
## lembrar das principais rotas. 





http://localhost:3000/evento/admin/65965e1c-8055-4795-b4a3-da93bbe97e31/familia2024